#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 142
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_fn = 1,
  anon_sym_EQ = 2,
  anon_sym_COLON = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_PIPE = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  sym_identifier = 13,
  sym_named_type = 14,
  sym_integer = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_STAR = 18,
  anon_sym_DOT = 19,
  anon_sym_DOT_DOT = 20,
  anon_sym_SEMI = 21,
  anon_sym_PERCENT = 22,
  anon_sym_SLASH = 23,
  anon_sym_LT = 24,
  anon_sym_GT = 25,
  anon_sym_LT_EQ = 26,
  anon_sym_GT_EQ = 27,
  sym_source_file = 28,
  sym__definition = 29,
  sym_function_definition = 30,
  sym_type_signature = 31,
  sym_type = 32,
  sym_start_type = 33,
  sym_closure = 34,
  sym_non_piecewise_closure = 35,
  sym_piecewise_closure = 36,
  sym_arm = 37,
  sym_expression = 38,
  sym_end_expression = 39,
  sym_end_term = 40,
  sym_term = 41,
  sym_param = 42,
  sym_pattern = 43,
  sym_param_name = 44,
  sym_literal = 45,
  sym_variable = 46,
  sym_symbol = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_start_type_repeat1 = 49,
  aux_sym_piecewise_closure_repeat1 = 50,
  aux_sym_arm_repeat1 = 51,
  aux_sym_term_repeat1 = 52,
  aux_sym_pattern_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PIPE] = "|",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_identifier] = "identifier",
  [sym_named_type] = "named_type",
  [sym_integer] = "integer",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_DOT] = ".",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_SEMI] = ";",
  [anon_sym_PERCENT] = "%",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_type_signature] = "type_signature",
  [sym_type] = "type",
  [sym_start_type] = "start_type",
  [sym_closure] = "closure",
  [sym_non_piecewise_closure] = "non_piecewise_closure",
  [sym_piecewise_closure] = "piecewise_closure",
  [sym_arm] = "arm",
  [sym_expression] = "expression",
  [sym_end_expression] = "end_expression",
  [sym_end_term] = "end_term",
  [sym_term] = "term",
  [sym_param] = "param",
  [sym_pattern] = "pattern",
  [sym_param_name] = "param_name",
  [sym_literal] = "literal",
  [sym_variable] = "variable",
  [sym_symbol] = "symbol",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_start_type_repeat1] = "start_type_repeat1",
  [aux_sym_piecewise_closure_repeat1] = "piecewise_closure_repeat1",
  [aux_sym_arm_repeat1] = "arm_repeat1",
  [aux_sym_term_repeat1] = "term_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_identifier] = sym_identifier,
  [sym_named_type] = sym_named_type,
  [sym_integer] = sym_integer,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_type_signature] = sym_type_signature,
  [sym_type] = sym_type,
  [sym_start_type] = sym_start_type,
  [sym_closure] = sym_closure,
  [sym_non_piecewise_closure] = sym_non_piecewise_closure,
  [sym_piecewise_closure] = sym_piecewise_closure,
  [sym_arm] = sym_arm,
  [sym_expression] = sym_expression,
  [sym_end_expression] = sym_end_expression,
  [sym_end_term] = sym_end_term,
  [sym_term] = sym_term,
  [sym_param] = sym_param,
  [sym_pattern] = sym_pattern,
  [sym_param_name] = sym_param_name,
  [sym_literal] = sym_literal,
  [sym_variable] = sym_variable,
  [sym_symbol] = sym_symbol,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_start_type_repeat1] = aux_sym_start_type_repeat1,
  [aux_sym_piecewise_closure_repeat1] = aux_sym_piecewise_closure_repeat1,
  [aux_sym_arm_repeat1] = aux_sym_arm_repeat1,
  [aux_sym_term_repeat1] = aux_sym_term_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_named_type] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_start_type] = {
    .visible = true,
    .named = true,
  },
  [sym_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_non_piecewise_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_piecewise_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_arm] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_end_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_end_term] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_param_name] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_piecewise_closure_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arm_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 19,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 27,
  [35] = 29,
  [36] = 26,
  [37] = 23,
  [38] = 21,
  [39] = 31,
  [40] = 30,
  [41] = 20,
  [42] = 28,
  [43] = 24,
  [44] = 33,
  [45] = 45,
  [46] = 32,
  [47] = 25,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 50,
  [52] = 49,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 84,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 85,
  [94] = 84,
  [95] = 88,
  [96] = 89,
  [97] = 89,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 88,
  [103] = 103,
  [104] = 85,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 21,
  [109] = 109,
  [110] = 110,
  [111] = 20,
  [112] = 112,
  [113] = 110,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 23,
  [121] = 121,
  [122] = 117,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 110,
  [128] = 109,
  [129] = 115,
  [130] = 121,
  [131] = 124,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '%') ADVANCE(37);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == ';') ADVANCE(36);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(40);
      if (lookahead == 'f') ADVANCE(20);
      if (lookahead == 't') ADVANCE(25);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '|') ADVANCE(17);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(37);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == '*') ADVANCE(33);
      if (lookahead == '+') ADVANCE(31);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == ';') ADVANCE(36);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(40);
      if (lookahead == 'f') ADVANCE(21);
      if (lookahead == 't') ADVANCE(25);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead == '|') ADVANCE(17);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == '}') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(24);
      if (lookahead == 'n') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_named_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 5},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 5},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 5},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 5},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 5},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 5},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 5},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 5},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 5},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 4},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_named_type] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(140),
    [sym__definition] = STATE(80),
    [sym_function_definition] = STATE(80),
    [aux_sym_source_file_repeat1] = STATE(80),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
  },
  [2] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(124),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [aux_sym_term_repeat1] = STATE(6),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [3] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(131),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [aux_sym_term_repeat1] = STATE(6),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [4] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(121),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [aux_sym_term_repeat1] = STATE(2),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [5] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(130),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [aux_sym_term_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [6] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(139),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [aux_sym_term_repeat1] = STATE(6),
    [anon_sym_EQ] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(34),
    [anon_sym_RPAREN] = ACTIONS(37),
    [anon_sym_LBRACE] = ACTIONS(39),
    [anon_sym_PIPE] = ACTIONS(42),
    [anon_sym_true] = ACTIONS(45),
    [anon_sym_false] = ACTIONS(45),
    [sym_identifier] = ACTIONS(48),
    [sym_integer] = ACTIONS(51),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_STAR] = ACTIONS(31),
    [anon_sym_DOT] = ACTIONS(54),
    [anon_sym_DOT_DOT] = ACTIONS(31),
    [anon_sym_SEMI] = ACTIONS(31),
    [anon_sym_PERCENT] = ACTIONS(31),
    [anon_sym_SLASH] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(54),
    [anon_sym_GT] = ACTIONS(54),
    [anon_sym_LT_EQ] = ACTIONS(31),
    [anon_sym_GT_EQ] = ACTIONS(31),
  },
  [7] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(129),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [8] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(115),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [9] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(71),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [10] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(42),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(17),
    [sym_end_expression] = STATE(71),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(46),
    [sym_literal] = STATE(42),
    [sym_variable] = STATE(42),
    [sym_symbol] = STATE(42),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_PIPE] = ACTIONS(67),
    [anon_sym_true] = ACTIONS(69),
    [anon_sym_false] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [sym_integer] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(75),
    [anon_sym_DOT_DOT] = ACTIONS(61),
    [anon_sym_SEMI] = ACTIONS(61),
    [anon_sym_PERCENT] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_LT_EQ] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(61),
  },
  [11] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(78),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [12] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(42),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(17),
    [sym_end_expression] = STATE(78),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(46),
    [sym_literal] = STATE(42),
    [sym_variable] = STATE(42),
    [sym_symbol] = STATE(42),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_PIPE] = ACTIONS(67),
    [anon_sym_true] = ACTIONS(69),
    [anon_sym_false] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [sym_integer] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(75),
    [anon_sym_DOT_DOT] = ACTIONS(61),
    [anon_sym_SEMI] = ACTIONS(61),
    [anon_sym_PERCENT] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_LT_EQ] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(61),
  },
  [13] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(18),
    [sym_end_expression] = STATE(77),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(32),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [14] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(42),
    [sym_arm] = STATE(76),
    [sym_expression] = STATE(17),
    [sym_end_expression] = STATE(77),
    [sym_end_term] = STATE(75),
    [sym_term] = STATE(46),
    [sym_literal] = STATE(42),
    [sym_variable] = STATE(42),
    [sym_symbol] = STATE(42),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_PIPE] = ACTIONS(67),
    [anon_sym_true] = ACTIONS(69),
    [anon_sym_false] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [sym_integer] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(75),
    [anon_sym_DOT_DOT] = ACTIONS(61),
    [anon_sym_SEMI] = ACTIONS(61),
    [anon_sym_PERCENT] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_LT_EQ] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(61),
  },
  [15] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(42),
    [sym_arm] = STATE(76),
    [sym_end_term] = STATE(74),
    [sym_term] = STATE(44),
    [sym_literal] = STATE(42),
    [sym_variable] = STATE(42),
    [sym_symbol] = STATE(42),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_LBRACE] = ACTIONS(65),
    [anon_sym_PIPE] = ACTIONS(67),
    [anon_sym_true] = ACTIONS(69),
    [anon_sym_false] = ACTIONS(69),
    [sym_identifier] = ACTIONS(71),
    [sym_integer] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(61),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(75),
    [anon_sym_DOT_DOT] = ACTIONS(61),
    [anon_sym_SEMI] = ACTIONS(61),
    [anon_sym_PERCENT] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_LT_EQ] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(61),
  },
  [16] = {
    [sym_non_piecewise_closure] = STATE(79),
    [sym_piecewise_closure] = STATE(28),
    [sym_arm] = STATE(76),
    [sym_end_term] = STATE(74),
    [sym_term] = STATE(33),
    [sym_literal] = STATE(28),
    [sym_variable] = STATE(28),
    [sym_symbol] = STATE(28),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_integer,
    STATE(15), 1,
      sym_term,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    STATE(28), 4,
      sym_piecewise_closure,
      sym_literal,
      sym_variable,
      sym_symbol,
    ACTIONS(7), 10,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [43] = 9,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_integer,
    STATE(16), 1,
      sym_term,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(23), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    STATE(28), 4,
      sym_piecewise_closure,
      sym_literal,
      sym_variable,
      sym_symbol,
    ACTIONS(7), 10,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [86] = 2,
    ACTIONS(79), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 17,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [115] = 2,
    ACTIONS(83), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [143] = 2,
    ACTIONS(87), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [171] = 2,
    ACTIONS(79), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [199] = 2,
    ACTIONS(91), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [227] = 2,
    ACTIONS(95), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [255] = 2,
    ACTIONS(99), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [283] = 2,
    ACTIONS(103), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [311] = 2,
    ACTIONS(107), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(105), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [339] = 2,
    ACTIONS(111), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [367] = 2,
    ACTIONS(115), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(113), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [395] = 2,
    ACTIONS(119), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(117), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [423] = 2,
    ACTIONS(123), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(121), 17,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [451] = 3,
    ACTIONS(127), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(129), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 13,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [480] = 3,
    ACTIONS(127), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(133), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 13,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [509] = 2,
    ACTIONS(107), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(105), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [535] = 2,
    ACTIONS(115), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(113), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [561] = 2,
    ACTIONS(103), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(101), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [587] = 2,
    ACTIONS(91), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [613] = 2,
    ACTIONS(87), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [639] = 2,
    ACTIONS(123), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(121), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [665] = 2,
    ACTIONS(119), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(117), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [691] = 2,
    ACTIONS(83), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [717] = 2,
    ACTIONS(111), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(109), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [743] = 2,
    ACTIONS(95), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(93), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [769] = 4,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(135), 1,
      anon_sym_fn,
    ACTIONS(133), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 13,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [799] = 2,
    ACTIONS(137), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(37), 15,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PIPE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [825] = 4,
    ACTIONS(127), 1,
      ts_builtin_sym_end,
    ACTIONS(135), 1,
      anon_sym_fn,
    ACTIONS(129), 6,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(125), 13,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [855] = 2,
    ACTIONS(99), 7,
      anon_sym_fn,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 14,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [881] = 9,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 1,
      anon_sym_PIPE,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(150), 1,
      sym_integer,
    STATE(48), 1,
      aux_sym_arm_repeat1,
    STATE(116), 1,
      sym_pattern,
    STATE(132), 1,
      sym_param,
    ACTIONS(144), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_param_name,
      sym_literal,
  [911] = 9,
    ACTIONS(73), 1,
      sym_integer,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    ACTIONS(155), 1,
      anon_sym_PIPE,
    ACTIONS(157), 1,
      sym_identifier,
    STATE(48), 1,
      aux_sym_arm_repeat1,
    STATE(109), 1,
      sym_param,
    STATE(116), 1,
      sym_pattern,
    ACTIONS(69), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_param_name,
      sym_literal,
  [941] = 9,
    ACTIONS(73), 1,
      sym_integer,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_PIPE,
    STATE(52), 1,
      aux_sym_arm_repeat1,
    STATE(116), 1,
      sym_pattern,
    STATE(122), 1,
      sym_param,
    ACTIONS(69), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_param_name,
      sym_literal,
  [971] = 9,
    ACTIONS(73), 1,
      sym_integer,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(161), 1,
      anon_sym_PIPE,
    STATE(49), 1,
      aux_sym_arm_repeat1,
    STATE(116), 1,
      sym_pattern,
    STATE(117), 1,
      sym_param,
    ACTIONS(69), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_param_name,
      sym_literal,
  [1001] = 9,
    ACTIONS(73), 1,
      sym_integer,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(163), 1,
      anon_sym_PIPE,
    STATE(48), 1,
      aux_sym_arm_repeat1,
    STATE(116), 1,
      sym_pattern,
    STATE(128), 1,
      sym_param,
    ACTIONS(69), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_param_name,
      sym_literal,
  [1031] = 8,
    ACTIONS(73), 1,
      sym_integer,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    STATE(55), 1,
      aux_sym_pattern_repeat1,
    STATE(112), 1,
      sym_pattern,
    ACTIONS(69), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_param_name,
      sym_literal,
  [1058] = 8,
    ACTIONS(73), 1,
      sym_integer,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      aux_sym_pattern_repeat1,
    STATE(118), 1,
      sym_pattern,
    ACTIONS(69), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_param_name,
      sym_literal,
  [1085] = 8,
    ACTIONS(169), 1,
      anon_sym_LPAREN,
    ACTIONS(172), 1,
      anon_sym_RPAREN,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(180), 1,
      sym_integer,
    STATE(55), 1,
      aux_sym_pattern_repeat1,
    STATE(133), 1,
      sym_pattern,
    ACTIONS(174), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_param_name,
      sym_literal,
  [1112] = 7,
    ACTIONS(73), 1,
      sym_integer,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
    STATE(137), 1,
      sym_pattern,
    ACTIONS(69), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_param_name,
      sym_literal,
  [1136] = 2,
    ACTIONS(142), 3,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      sym_integer,
    ACTIONS(185), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [1147] = 1,
    ACTIONS(187), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [1156] = 1,
    ACTIONS(189), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [1165] = 1,
    ACTIONS(191), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [1174] = 2,
    ACTIONS(172), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_integer,
    ACTIONS(193), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [1185] = 6,
    ACTIONS(195), 1,
      anon_sym_LPAREN,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    ACTIONS(200), 1,
      sym_named_type,
    STATE(62), 1,
      aux_sym_start_type_repeat1,
    STATE(66), 1,
      sym_start_type,
    STATE(135), 1,
      sym_type,
  [1204] = 1,
    ACTIONS(203), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [1213] = 1,
    ACTIONS(205), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [1222] = 1,
    ACTIONS(207), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [1231] = 4,
    ACTIONS(211), 1,
      anon_sym_LPAREN,
    ACTIONS(213), 1,
      sym_named_type,
    STATE(141), 1,
      sym_start_type,
    ACTIONS(209), 3,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1246] = 6,
    ACTIONS(211), 1,
      anon_sym_LPAREN,
    ACTIONS(213), 1,
      sym_named_type,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_start_type_repeat1,
    STATE(66), 1,
      sym_start_type,
    STATE(119), 1,
      sym_type,
  [1265] = 5,
    ACTIONS(67), 1,
      anon_sym_PIPE,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(76), 1,
      sym_arm,
    STATE(126), 1,
      sym_closure,
    STATE(123), 2,
      sym_non_piecewise_closure,
      sym_piecewise_closure,
  [1282] = 5,
    ACTIONS(67), 1,
      anon_sym_PIPE,
    ACTIONS(217), 1,
      anon_sym_LBRACE,
    STATE(76), 1,
      sym_arm,
    STATE(105), 1,
      sym_closure,
    STATE(123), 2,
      sym_non_piecewise_closure,
      sym_piecewise_closure,
  [1299] = 6,
    ACTIONS(211), 1,
      anon_sym_LPAREN,
    ACTIONS(213), 1,
      sym_named_type,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_start_type,
    STATE(67), 1,
      aux_sym_start_type_repeat1,
    STATE(106), 1,
      sym_type,
  [1318] = 1,
    ACTIONS(221), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1326] = 5,
    ACTIONS(211), 1,
      anon_sym_LPAREN,
    ACTIONS(213), 1,
      sym_named_type,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_start_type,
    STATE(114), 1,
      sym_type,
  [1342] = 3,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
    ACTIONS(227), 1,
      anon_sym_fn,
    STATE(73), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1354] = 1,
    ACTIONS(230), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1362] = 1,
    ACTIONS(232), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1370] = 1,
    ACTIONS(234), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1378] = 1,
    ACTIONS(236), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1386] = 1,
    ACTIONS(238), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1394] = 1,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1402] = 3,
    ACTIONS(5), 1,
      anon_sym_fn,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
    STATE(73), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1414] = 4,
    ACTIONS(211), 1,
      anon_sym_LPAREN,
    ACTIONS(213), 1,
      sym_named_type,
    STATE(66), 1,
      sym_start_type,
    STATE(98), 1,
      sym_type,
  [1427] = 4,
    ACTIONS(211), 1,
      anon_sym_LPAREN,
    ACTIONS(213), 1,
      sym_named_type,
    STATE(66), 1,
      sym_start_type,
    STATE(138), 1,
      sym_type,
  [1440] = 1,
    ACTIONS(242), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1446] = 3,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    STATE(103), 1,
      aux_sym_piecewise_closure_repeat1,
  [1456] = 3,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(248), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      sym_arm,
  [1466] = 1,
    ACTIONS(198), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_named_type,
  [1472] = 3,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
    STATE(103), 1,
      aux_sym_piecewise_closure_repeat1,
  [1482] = 3,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      sym_arm,
  [1492] = 3,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RBRACE,
    STATE(87), 1,
      aux_sym_piecewise_closure_repeat1,
  [1502] = 1,
    ACTIONS(258), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1508] = 3,
    ACTIONS(260), 1,
      anon_sym_EQ,
    ACTIONS(262), 1,
      anon_sym_COLON,
    STATE(134), 1,
      sym_type_signature,
  [1518] = 1,
    ACTIONS(264), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1524] = 3,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      sym_arm,
  [1534] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    STATE(103), 1,
      aux_sym_piecewise_closure_repeat1,
  [1544] = 3,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      sym_arm,
  [1554] = 3,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
    STATE(94), 1,
      aux_sym_piecewise_closure_repeat1,
  [1564] = 3,
    ACTIONS(276), 1,
      anon_sym_COMMA,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      aux_sym_piecewise_closure_repeat1,
  [1574] = 1,
    ACTIONS(280), 3,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1580] = 1,
    ACTIONS(282), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1586] = 1,
    ACTIONS(284), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1592] = 1,
    ACTIONS(286), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1598] = 3,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(246), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      sym_arm,
  [1608] = 3,
    ACTIONS(288), 1,
      anon_sym_COMMA,
    ACTIONS(291), 1,
      anon_sym_RBRACE,
    STATE(103), 1,
      aux_sym_piecewise_closure_repeat1,
  [1618] = 3,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(293), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      sym_arm,
  [1628] = 1,
    ACTIONS(295), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1633] = 2,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    ACTIONS(297), 1,
      anon_sym_COMMA,
  [1640] = 1,
    ACTIONS(291), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1645] = 1,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1650] = 2,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(301), 1,
      anon_sym_PIPE,
  [1657] = 2,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    STATE(89), 1,
      sym_arm,
  [1664] = 1,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1669] = 2,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    ACTIONS(305), 1,
      anon_sym_COMMA,
  [1676] = 2,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    STATE(96), 1,
      sym_arm,
  [1683] = 2,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    ACTIONS(309), 1,
      anon_sym_COMMA,
  [1690] = 2,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
    ACTIONS(313), 1,
      anon_sym_COMMA,
  [1697] = 1,
    ACTIONS(315), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1702] = 2,
    ACTIONS(155), 1,
      anon_sym_PIPE,
    ACTIONS(299), 1,
      anon_sym_COMMA,
  [1709] = 2,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    ACTIONS(305), 1,
      anon_sym_COMMA,
  [1716] = 2,
    ACTIONS(297), 1,
      anon_sym_COMMA,
    ACTIONS(317), 1,
      anon_sym_RPAREN,
  [1723] = 1,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1728] = 2,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(319), 1,
      anon_sym_COMMA,
  [1735] = 2,
    ACTIONS(163), 1,
      anon_sym_PIPE,
    ACTIONS(299), 1,
      anon_sym_COMMA,
  [1742] = 1,
    ACTIONS(321), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1747] = 2,
    ACTIONS(319), 1,
      anon_sym_COMMA,
    ACTIONS(323), 1,
      anon_sym_RPAREN,
  [1754] = 2,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    STATE(107), 1,
      sym_arm,
  [1761] = 1,
    ACTIONS(325), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1766] = 2,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    STATE(97), 1,
      sym_arm,
  [1773] = 2,
    ACTIONS(299), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_PIPE,
  [1780] = 2,
    ACTIONS(329), 1,
      anon_sym_RPAREN,
    ACTIONS(331), 1,
      anon_sym_COMMA,
  [1787] = 2,
    ACTIONS(25), 1,
      anon_sym_RPAREN,
    ACTIONS(319), 1,
      anon_sym_COMMA,
  [1794] = 2,
    ACTIONS(319), 1,
      anon_sym_COMMA,
    ACTIONS(333), 1,
      anon_sym_RPAREN,
  [1801] = 1,
    ACTIONS(299), 1,
      anon_sym_COMMA,
  [1805] = 1,
    ACTIONS(305), 1,
      anon_sym_COMMA,
  [1809] = 1,
    ACTIONS(335), 1,
      anon_sym_EQ,
  [1813] = 1,
    ACTIONS(297), 1,
      anon_sym_COMMA,
  [1817] = 1,
    ACTIONS(337), 1,
      sym_identifier,
  [1821] = 1,
    ACTIONS(339), 1,
      anon_sym_COMMA,
  [1825] = 1,
    ACTIONS(341), 1,
      anon_sym_EQ,
  [1829] = 1,
    ACTIONS(319), 1,
      anon_sym_COMMA,
  [1833] = 1,
    ACTIONS(343), 1,
      ts_builtin_sym_end,
  [1837] = 1,
    ACTIONS(345), 1,
      anon_sym_DASH_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 43,
  [SMALL_STATE(19)] = 86,
  [SMALL_STATE(20)] = 115,
  [SMALL_STATE(21)] = 143,
  [SMALL_STATE(22)] = 171,
  [SMALL_STATE(23)] = 199,
  [SMALL_STATE(24)] = 227,
  [SMALL_STATE(25)] = 255,
  [SMALL_STATE(26)] = 283,
  [SMALL_STATE(27)] = 311,
  [SMALL_STATE(28)] = 339,
  [SMALL_STATE(29)] = 367,
  [SMALL_STATE(30)] = 395,
  [SMALL_STATE(31)] = 423,
  [SMALL_STATE(32)] = 451,
  [SMALL_STATE(33)] = 480,
  [SMALL_STATE(34)] = 509,
  [SMALL_STATE(35)] = 535,
  [SMALL_STATE(36)] = 561,
  [SMALL_STATE(37)] = 587,
  [SMALL_STATE(38)] = 613,
  [SMALL_STATE(39)] = 639,
  [SMALL_STATE(40)] = 665,
  [SMALL_STATE(41)] = 691,
  [SMALL_STATE(42)] = 717,
  [SMALL_STATE(43)] = 743,
  [SMALL_STATE(44)] = 769,
  [SMALL_STATE(45)] = 799,
  [SMALL_STATE(46)] = 825,
  [SMALL_STATE(47)] = 855,
  [SMALL_STATE(48)] = 881,
  [SMALL_STATE(49)] = 911,
  [SMALL_STATE(50)] = 941,
  [SMALL_STATE(51)] = 971,
  [SMALL_STATE(52)] = 1001,
  [SMALL_STATE(53)] = 1031,
  [SMALL_STATE(54)] = 1058,
  [SMALL_STATE(55)] = 1085,
  [SMALL_STATE(56)] = 1112,
  [SMALL_STATE(57)] = 1136,
  [SMALL_STATE(58)] = 1147,
  [SMALL_STATE(59)] = 1156,
  [SMALL_STATE(60)] = 1165,
  [SMALL_STATE(61)] = 1174,
  [SMALL_STATE(62)] = 1185,
  [SMALL_STATE(63)] = 1204,
  [SMALL_STATE(64)] = 1213,
  [SMALL_STATE(65)] = 1222,
  [SMALL_STATE(66)] = 1231,
  [SMALL_STATE(67)] = 1246,
  [SMALL_STATE(68)] = 1265,
  [SMALL_STATE(69)] = 1282,
  [SMALL_STATE(70)] = 1299,
  [SMALL_STATE(71)] = 1318,
  [SMALL_STATE(72)] = 1326,
  [SMALL_STATE(73)] = 1342,
  [SMALL_STATE(74)] = 1354,
  [SMALL_STATE(75)] = 1362,
  [SMALL_STATE(76)] = 1370,
  [SMALL_STATE(77)] = 1378,
  [SMALL_STATE(78)] = 1386,
  [SMALL_STATE(79)] = 1394,
  [SMALL_STATE(80)] = 1402,
  [SMALL_STATE(81)] = 1414,
  [SMALL_STATE(82)] = 1427,
  [SMALL_STATE(83)] = 1440,
  [SMALL_STATE(84)] = 1446,
  [SMALL_STATE(85)] = 1456,
  [SMALL_STATE(86)] = 1466,
  [SMALL_STATE(87)] = 1472,
  [SMALL_STATE(88)] = 1482,
  [SMALL_STATE(89)] = 1492,
  [SMALL_STATE(90)] = 1502,
  [SMALL_STATE(91)] = 1508,
  [SMALL_STATE(92)] = 1518,
  [SMALL_STATE(93)] = 1524,
  [SMALL_STATE(94)] = 1534,
  [SMALL_STATE(95)] = 1544,
  [SMALL_STATE(96)] = 1554,
  [SMALL_STATE(97)] = 1564,
  [SMALL_STATE(98)] = 1574,
  [SMALL_STATE(99)] = 1580,
  [SMALL_STATE(100)] = 1586,
  [SMALL_STATE(101)] = 1592,
  [SMALL_STATE(102)] = 1598,
  [SMALL_STATE(103)] = 1608,
  [SMALL_STATE(104)] = 1618,
  [SMALL_STATE(105)] = 1628,
  [SMALL_STATE(106)] = 1633,
  [SMALL_STATE(107)] = 1640,
  [SMALL_STATE(108)] = 1645,
  [SMALL_STATE(109)] = 1650,
  [SMALL_STATE(110)] = 1657,
  [SMALL_STATE(111)] = 1664,
  [SMALL_STATE(112)] = 1669,
  [SMALL_STATE(113)] = 1676,
  [SMALL_STATE(114)] = 1683,
  [SMALL_STATE(115)] = 1690,
  [SMALL_STATE(116)] = 1697,
  [SMALL_STATE(117)] = 1702,
  [SMALL_STATE(118)] = 1709,
  [SMALL_STATE(119)] = 1716,
  [SMALL_STATE(120)] = 1723,
  [SMALL_STATE(121)] = 1728,
  [SMALL_STATE(122)] = 1735,
  [SMALL_STATE(123)] = 1742,
  [SMALL_STATE(124)] = 1747,
  [SMALL_STATE(125)] = 1754,
  [SMALL_STATE(126)] = 1761,
  [SMALL_STATE(127)] = 1766,
  [SMALL_STATE(128)] = 1773,
  [SMALL_STATE(129)] = 1780,
  [SMALL_STATE(130)] = 1787,
  [SMALL_STATE(131)] = 1794,
  [SMALL_STATE(132)] = 1801,
  [SMALL_STATE(133)] = 1805,
  [SMALL_STATE(134)] = 1809,
  [SMALL_STATE(135)] = 1813,
  [SMALL_STATE(136)] = 1817,
  [SMALL_STATE(137)] = 1821,
  [SMALL_STATE(138)] = 1825,
  [SMALL_STATE(139)] = 1829,
  [SMALL_STATE(140)] = 1833,
  [SMALL_STATE(141)] = 1837,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(31),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(7),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(110),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(50),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(22),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(30),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(22),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(31),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_piecewise_closure, 3),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_piecewise_closure, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_piecewise_closure, 4),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_piecewise_closure, 4),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_piecewise_closure, 5),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_piecewise_closure, 5),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 6),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 6),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 5),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 5),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 4),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 2),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_term, 1),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_term, 1),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2),
  [139] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(56),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arm_repeat1, 2),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(19),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(99),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(19),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(56),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(19),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(99),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(19),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arm_repeat1, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 6),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_type_repeat1, 2), SHIFT_REPEAT(72),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_type_repeat1, 2),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_type_repeat1, 2), SHIFT_REPEAT(63),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 5),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arm, 5),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(136),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_expression, 3),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_expression, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_non_piecewise_closure, 1),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arm, 4),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arm, 3),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 5),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 6),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_name, 1),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 4),
  [288] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_piecewise_closure_repeat1, 2), SHIFT_REPEAT(125),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_piecewise_closure_repeat1, 2),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_closure, 1),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [325] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [341] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_signature, 2),
  [343] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_curse(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
