#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 99
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_fn = 1,
  anon_sym_EQ = 2,
  anon_sym_COLON = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_PIPE = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  anon_sym_in = 13,
  sym_identifier = 14,
  sym_named_type = 15,
  sym_integer = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_DOT = 20,
  anon_sym_DOT_DOT = 21,
  anon_sym_SEMI = 22,
  anon_sym_PERCENT = 23,
  anon_sym_SLASH = 24,
  anon_sym_LT = 25,
  anon_sym_GT = 26,
  anon_sym_LT_EQ = 27,
  anon_sym_GT_EQ = 28,
  sym_source_file = 29,
  sym__definition = 30,
  sym_function_definition = 31,
  sym_type_signature = 32,
  sym_type = 33,
  sym_start_type = 34,
  sym_closure = 35,
  sym_non_piecewise_closure = 36,
  sym_piecewise_closure = 37,
  sym_arm = 38,
  sym_expression = 39,
  sym_end_expression = 40,
  sym_end_term = 41,
  sym_term = 42,
  sym_param = 43,
  sym_pattern = 44,
  sym_param_name = 45,
  sym_literal = 46,
  sym_symbol = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_start_type_repeat1 = 49,
  aux_sym_piecewise_closure_repeat1 = 50,
  aux_sym_arm_repeat1 = 51,
  aux_sym_term_repeat1 = 52,
  aux_sym_pattern_repeat1 = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PIPE] = "|",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_in] = "in",
  [sym_identifier] = "identifier",
  [sym_named_type] = "named_type",
  [sym_integer] = "integer",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_DOT] = ".",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_SEMI] = ";",
  [anon_sym_PERCENT] = "%",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_type_signature] = "type_signature",
  [sym_type] = "type",
  [sym_start_type] = "start_type",
  [sym_closure] = "closure",
  [sym_non_piecewise_closure] = "non_piecewise_closure",
  [sym_piecewise_closure] = "piecewise_closure",
  [sym_arm] = "arm",
  [sym_expression] = "expression",
  [sym_end_expression] = "end_expression",
  [sym_end_term] = "end_term",
  [sym_term] = "term",
  [sym_param] = "param",
  [sym_pattern] = "pattern",
  [sym_param_name] = "param_name",
  [sym_literal] = "literal",
  [sym_symbol] = "symbol",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_start_type_repeat1] = "start_type_repeat1",
  [aux_sym_piecewise_closure_repeat1] = "piecewise_closure_repeat1",
  [aux_sym_arm_repeat1] = "arm_repeat1",
  [aux_sym_term_repeat1] = "term_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_in] = anon_sym_in,
  [sym_identifier] = sym_identifier,
  [sym_named_type] = sym_named_type,
  [sym_integer] = sym_integer,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_type_signature] = sym_type_signature,
  [sym_type] = sym_type,
  [sym_start_type] = sym_start_type,
  [sym_closure] = sym_closure,
  [sym_non_piecewise_closure] = sym_non_piecewise_closure,
  [sym_piecewise_closure] = sym_piecewise_closure,
  [sym_arm] = sym_arm,
  [sym_expression] = sym_expression,
  [sym_end_expression] = sym_end_expression,
  [sym_end_term] = sym_end_term,
  [sym_term] = sym_term,
  [sym_param] = sym_param,
  [sym_pattern] = sym_pattern,
  [sym_param_name] = sym_param_name,
  [sym_literal] = sym_literal,
  [sym_symbol] = sym_symbol,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_start_type_repeat1] = aux_sym_start_type_repeat1,
  [aux_sym_piecewise_closure_repeat1] = aux_sym_piecewise_closure_repeat1,
  [aux_sym_arm_repeat1] = aux_sym_arm_repeat1,
  [aux_sym_term_repeat1] = aux_sym_term_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_named_type] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_start_type] = {
    .visible = true,
    .named = true,
  },
  [sym_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_non_piecewise_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_piecewise_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_arm] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_end_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_end_term] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_param_name] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_piecewise_closure_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arm_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '%') ADVANCE(46);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '+') ADVANCE(40);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == ';') ADVANCE(45);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(49);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(29);
      if (lookahead == 'i') ADVANCE(33);
      if (lookahead == 't') ADVANCE(34);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(6);
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(4);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_in);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_named_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 11},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [sym_named_type] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(97),
    [sym__definition] = STATE(48),
    [sym_function_definition] = STATE(48),
    [aux_sym_source_file_repeat1] = STATE(48),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
  },
  [2] = {
    [sym_non_piecewise_closure] = STATE(49),
    [sym_piecewise_closure] = STATE(19),
    [sym_arm] = STATE(55),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(98),
    [sym_end_term] = STATE(51),
    [sym_term] = STATE(22),
    [sym_literal] = STATE(19),
    [sym_symbol] = STATE(19),
    [aux_sym_term_repeat1] = STATE(2),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(10),
    [anon_sym_RPAREN] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_PIPE] = ACTIONS(18),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
    [anon_sym_in] = ACTIONS(21),
    [sym_integer] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(24),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(24),
    [anon_sym_GT] = ACTIONS(24),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [3] = {
    [sym_non_piecewise_closure] = STATE(49),
    [sym_piecewise_closure] = STATE(19),
    [sym_arm] = STATE(55),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(76),
    [sym_end_term] = STATE(51),
    [sym_term] = STATE(22),
    [sym_literal] = STATE(19),
    [sym_symbol] = STATE(19),
    [aux_sym_term_repeat1] = STATE(2),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
    [anon_sym_in] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(39),
    [anon_sym_DOT_DOT] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(27),
  },
  [4] = {
    [sym_non_piecewise_closure] = STATE(49),
    [sym_piecewise_closure] = STATE(19),
    [sym_arm] = STATE(55),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(87),
    [sym_end_term] = STATE(51),
    [sym_term] = STATE(22),
    [sym_literal] = STATE(19),
    [sym_symbol] = STATE(19),
    [aux_sym_term_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
    [anon_sym_in] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(39),
    [anon_sym_DOT_DOT] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(27),
  },
  [5] = {
    [sym_non_piecewise_closure] = STATE(49),
    [sym_piecewise_closure] = STATE(19),
    [sym_arm] = STATE(55),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(86),
    [sym_end_term] = STATE(51),
    [sym_term] = STATE(22),
    [sym_literal] = STATE(19),
    [sym_symbol] = STATE(19),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
    [anon_sym_in] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(39),
    [anon_sym_DOT_DOT] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(27),
  },
  [6] = {
    [sym_non_piecewise_closure] = STATE(49),
    [sym_piecewise_closure] = STATE(19),
    [sym_arm] = STATE(55),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(50),
    [sym_end_term] = STATE(51),
    [sym_term] = STATE(22),
    [sym_literal] = STATE(19),
    [sym_symbol] = STATE(19),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
    [anon_sym_in] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(39),
    [anon_sym_DOT_DOT] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(27),
  },
  [7] = {
    [sym_non_piecewise_closure] = STATE(49),
    [sym_piecewise_closure] = STATE(19),
    [sym_arm] = STATE(55),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(47),
    [sym_end_term] = STATE(51),
    [sym_term] = STATE(22),
    [sym_literal] = STATE(19),
    [sym_symbol] = STATE(19),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
    [anon_sym_in] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(39),
    [anon_sym_DOT_DOT] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(27),
  },
  [8] = {
    [sym_non_piecewise_closure] = STATE(49),
    [sym_piecewise_closure] = STATE(19),
    [sym_arm] = STATE(55),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(53),
    [sym_end_term] = STATE(51),
    [sym_term] = STATE(22),
    [sym_literal] = STATE(19),
    [sym_symbol] = STATE(19),
    [anon_sym_EQ] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
    [anon_sym_in] = ACTIONS(37),
    [sym_integer] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_DOT] = ACTIONS(39),
    [anon_sym_DOT_DOT] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_GT_EQ] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      anon_sym_PIPE,
    STATE(21), 1,
      sym_term,
    STATE(49), 1,
      sym_non_piecewise_closure,
    STATE(52), 1,
      sym_end_term,
    STATE(55), 1,
      sym_arm,
    ACTIONS(39), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    STATE(19), 3,
      sym_piecewise_closure,
      sym_literal,
      sym_symbol,
    ACTIONS(37), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
    ACTIONS(27), 10,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [50] = 2,
    ACTIONS(47), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [80] = 2,
    ACTIONS(51), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [110] = 2,
    ACTIONS(55), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [140] = 2,
    ACTIONS(59), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [170] = 2,
    ACTIONS(63), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [200] = 2,
    ACTIONS(67), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [230] = 2,
    ACTIONS(71), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [260] = 2,
    ACTIONS(75), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(73), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [290] = 2,
    ACTIONS(79), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [320] = 2,
    ACTIONS(83), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [350] = 2,
    ACTIONS(87), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [380] = 3,
    ACTIONS(93), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(91), 16,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [411] = 3,
    ACTIONS(97), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(95), 16,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [442] = 7,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym_term,
    ACTIONS(39), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    STATE(19), 3,
      sym_piecewise_closure,
      sym_literal,
      sym_symbol,
    ACTIONS(37), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
    ACTIONS(27), 10,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [480] = 2,
    ACTIONS(99), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(13), 18,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [506] = 9,
    ACTIONS(37), 1,
      sym_integer,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 1,
      anon_sym_PIPE,
    ACTIONS(107), 1,
      sym_identifier,
    STATE(26), 1,
      aux_sym_arm_repeat1,
    STATE(73), 1,
      sym_pattern,
    STATE(88), 1,
      sym_param,
    STATE(64), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(105), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [537] = 9,
    ACTIONS(37), 1,
      sym_integer,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      sym_identifier,
    ACTIONS(109), 1,
      anon_sym_PIPE,
    STATE(27), 1,
      aux_sym_arm_repeat1,
    STATE(73), 1,
      sym_pattern,
    STATE(75), 1,
      sym_param,
    STATE(64), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(105), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [568] = 9,
    ACTIONS(111), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 1,
      anon_sym_PIPE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(122), 1,
      sym_integer,
    STATE(27), 1,
      aux_sym_arm_repeat1,
    STATE(73), 1,
      sym_pattern,
    STATE(89), 1,
      sym_param,
    STATE(64), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(116), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [599] = 8,
    ACTIONS(37), 1,
      sym_integer,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      sym_identifier,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_pattern_repeat1,
    STATE(84), 1,
      sym_pattern,
    STATE(64), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(105), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [627] = 8,
    ACTIONS(127), 1,
      anon_sym_LPAREN,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(138), 1,
      sym_integer,
    STATE(29), 1,
      aux_sym_pattern_repeat1,
    STATE(92), 1,
      sym_pattern,
    STATE(64), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(132), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [655] = 8,
    ACTIONS(37), 1,
      sym_integer,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_pattern_repeat1,
    STATE(77), 1,
      sym_pattern,
    STATE(64), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(105), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [683] = 7,
    ACTIONS(37), 1,
      sym_integer,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
    ACTIONS(107), 1,
      sym_identifier,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      sym_pattern,
    STATE(64), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(105), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [708] = 2,
    ACTIONS(130), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_integer,
    ACTIONS(145), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_identifier,
  [720] = 2,
    ACTIONS(114), 3,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      sym_integer,
    ACTIONS(147), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_identifier,
  [732] = 1,
    ACTIONS(149), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [741] = 5,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      anon_sym_PIPE,
    STATE(55), 1,
      sym_arm,
    STATE(82), 1,
      sym_closure,
    STATE(85), 2,
      sym_non_piecewise_closure,
      sym_piecewise_closure,
  [758] = 1,
    ACTIONS(151), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [767] = 5,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(35), 1,
      anon_sym_PIPE,
    STATE(55), 1,
      sym_arm,
    STATE(72), 1,
      sym_closure,
    STATE(85), 2,
      sym_non_piecewise_closure,
      sym_piecewise_closure,
  [784] = 6,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    ACTIONS(158), 1,
      sym_named_type,
    STATE(38), 1,
      aux_sym_start_type_repeat1,
    STATE(43), 1,
      sym_start_type,
    STATE(90), 1,
      sym_type,
  [803] = 1,
    ACTIONS(161), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [812] = 1,
    ACTIONS(163), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [821] = 6,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    ACTIONS(169), 1,
      sym_named_type,
    STATE(38), 1,
      aux_sym_start_type_repeat1,
    STATE(43), 1,
      sym_start_type,
    STATE(80), 1,
      sym_type,
  [840] = 1,
    ACTIONS(171), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [849] = 4,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 1,
      sym_named_type,
    STATE(93), 1,
      sym_start_type,
    ACTIONS(173), 3,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [864] = 1,
    ACTIONS(175), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [873] = 6,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 1,
      sym_named_type,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_start_type_repeat1,
    STATE(43), 1,
      sym_start_type,
    STATE(83), 1,
      sym_type,
  [892] = 5,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 1,
      sym_named_type,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_start_type,
    STATE(81), 1,
      sym_type,
  [908] = 1,
    ACTIONS(181), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [916] = 3,
    ACTIONS(5), 1,
      anon_sym_fn,
    ACTIONS(183), 1,
      ts_builtin_sym_end,
    STATE(54), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [928] = 1,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [936] = 1,
    ACTIONS(185), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [944] = 1,
    ACTIONS(187), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [952] = 1,
    ACTIONS(189), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [960] = 1,
    ACTIONS(191), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [968] = 3,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
    ACTIONS(195), 1,
      anon_sym_fn,
    STATE(54), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [980] = 1,
    ACTIONS(198), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [988] = 4,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 1,
      sym_named_type,
    STATE(43), 1,
      sym_start_type,
    STATE(91), 1,
      sym_type,
  [1001] = 4,
    ACTIONS(165), 1,
      anon_sym_LPAREN,
    ACTIONS(169), 1,
      sym_named_type,
    STATE(43), 1,
      sym_start_type,
    STATE(68), 1,
      sym_type,
  [1014] = 3,
    ACTIONS(35), 1,
      anon_sym_PIPE,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      sym_arm,
  [1024] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      aux_sym_piecewise_closure_repeat1,
  [1034] = 1,
    ACTIONS(207), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1040] = 1,
    ACTIONS(209), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1046] = 3,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      aux_sym_piecewise_closure_repeat1,
  [1056] = 3,
    ACTIONS(215), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      aux_sym_piecewise_closure_repeat1,
  [1066] = 1,
    ACTIONS(219), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1072] = 3,
    ACTIONS(35), 1,
      anon_sym_PIPE,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(78), 1,
      sym_arm,
  [1082] = 1,
    ACTIONS(221), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1088] = 1,
    ACTIONS(156), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_named_type,
  [1094] = 1,
    ACTIONS(223), 3,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1100] = 3,
    ACTIONS(225), 1,
      anon_sym_EQ,
    ACTIONS(227), 1,
      anon_sym_COLON,
    STATE(95), 1,
      sym_type_signature,
  [1110] = 1,
    ACTIONS(229), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1116] = 1,
    ACTIONS(231), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1122] = 1,
    ACTIONS(233), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1127] = 1,
    ACTIONS(235), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1132] = 2,
    ACTIONS(35), 1,
      anon_sym_PIPE,
    STATE(62), 1,
      sym_arm,
  [1139] = 2,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_PIPE,
  [1146] = 2,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
    ACTIONS(243), 1,
      anon_sym_COMMA,
  [1153] = 2,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(245), 1,
      anon_sym_COMMA,
  [1160] = 1,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1165] = 2,
    ACTIONS(35), 1,
      anon_sym_PIPE,
    STATE(78), 1,
      sym_arm,
  [1172] = 2,
    ACTIONS(247), 1,
      anon_sym_RPAREN,
    ACTIONS(249), 1,
      anon_sym_COMMA,
  [1179] = 2,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    ACTIONS(253), 1,
      anon_sym_COMMA,
  [1186] = 1,
    ACTIONS(255), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1191] = 2,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    ACTIONS(249), 1,
      anon_sym_COMMA,
  [1198] = 2,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
  [1205] = 1,
    ACTIONS(259), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1210] = 2,
    ACTIONS(261), 1,
      anon_sym_RPAREN,
    ACTIONS(263), 1,
      anon_sym_COMMA,
  [1217] = 2,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(243), 1,
      anon_sym_COMMA,
  [1224] = 2,
    ACTIONS(109), 1,
      anon_sym_PIPE,
    ACTIONS(237), 1,
      anon_sym_COMMA,
  [1231] = 1,
    ACTIONS(237), 1,
      anon_sym_COMMA,
  [1235] = 1,
    ACTIONS(249), 1,
      anon_sym_COMMA,
  [1239] = 1,
    ACTIONS(265), 1,
      anon_sym_EQ,
  [1243] = 1,
    ACTIONS(245), 1,
      anon_sym_COMMA,
  [1247] = 1,
    ACTIONS(267), 1,
      anon_sym_DASH_GT,
  [1251] = 1,
    ACTIONS(269), 1,
      sym_identifier,
  [1255] = 1,
    ACTIONS(271), 1,
      anon_sym_EQ,
  [1259] = 1,
    ACTIONS(273), 1,
      anon_sym_COMMA,
  [1263] = 1,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
  [1267] = 1,
    ACTIONS(243), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 50,
  [SMALL_STATE(11)] = 80,
  [SMALL_STATE(12)] = 110,
  [SMALL_STATE(13)] = 140,
  [SMALL_STATE(14)] = 170,
  [SMALL_STATE(15)] = 200,
  [SMALL_STATE(16)] = 230,
  [SMALL_STATE(17)] = 260,
  [SMALL_STATE(18)] = 290,
  [SMALL_STATE(19)] = 320,
  [SMALL_STATE(20)] = 350,
  [SMALL_STATE(21)] = 380,
  [SMALL_STATE(22)] = 411,
  [SMALL_STATE(23)] = 442,
  [SMALL_STATE(24)] = 480,
  [SMALL_STATE(25)] = 506,
  [SMALL_STATE(26)] = 537,
  [SMALL_STATE(27)] = 568,
  [SMALL_STATE(28)] = 599,
  [SMALL_STATE(29)] = 627,
  [SMALL_STATE(30)] = 655,
  [SMALL_STATE(31)] = 683,
  [SMALL_STATE(32)] = 708,
  [SMALL_STATE(33)] = 720,
  [SMALL_STATE(34)] = 732,
  [SMALL_STATE(35)] = 741,
  [SMALL_STATE(36)] = 758,
  [SMALL_STATE(37)] = 767,
  [SMALL_STATE(38)] = 784,
  [SMALL_STATE(39)] = 803,
  [SMALL_STATE(40)] = 812,
  [SMALL_STATE(41)] = 821,
  [SMALL_STATE(42)] = 840,
  [SMALL_STATE(43)] = 849,
  [SMALL_STATE(44)] = 864,
  [SMALL_STATE(45)] = 873,
  [SMALL_STATE(46)] = 892,
  [SMALL_STATE(47)] = 908,
  [SMALL_STATE(48)] = 916,
  [SMALL_STATE(49)] = 928,
  [SMALL_STATE(50)] = 936,
  [SMALL_STATE(51)] = 944,
  [SMALL_STATE(52)] = 952,
  [SMALL_STATE(53)] = 960,
  [SMALL_STATE(54)] = 968,
  [SMALL_STATE(55)] = 980,
  [SMALL_STATE(56)] = 988,
  [SMALL_STATE(57)] = 1001,
  [SMALL_STATE(58)] = 1014,
  [SMALL_STATE(59)] = 1024,
  [SMALL_STATE(60)] = 1034,
  [SMALL_STATE(61)] = 1040,
  [SMALL_STATE(62)] = 1046,
  [SMALL_STATE(63)] = 1056,
  [SMALL_STATE(64)] = 1066,
  [SMALL_STATE(65)] = 1072,
  [SMALL_STATE(66)] = 1082,
  [SMALL_STATE(67)] = 1088,
  [SMALL_STATE(68)] = 1094,
  [SMALL_STATE(69)] = 1100,
  [SMALL_STATE(70)] = 1110,
  [SMALL_STATE(71)] = 1116,
  [SMALL_STATE(72)] = 1122,
  [SMALL_STATE(73)] = 1127,
  [SMALL_STATE(74)] = 1132,
  [SMALL_STATE(75)] = 1139,
  [SMALL_STATE(76)] = 1146,
  [SMALL_STATE(77)] = 1153,
  [SMALL_STATE(78)] = 1160,
  [SMALL_STATE(79)] = 1165,
  [SMALL_STATE(80)] = 1172,
  [SMALL_STATE(81)] = 1179,
  [SMALL_STATE(82)] = 1186,
  [SMALL_STATE(83)] = 1191,
  [SMALL_STATE(84)] = 1198,
  [SMALL_STATE(85)] = 1205,
  [SMALL_STATE(86)] = 1210,
  [SMALL_STATE(87)] = 1217,
  [SMALL_STATE(88)] = 1224,
  [SMALL_STATE(89)] = 1231,
  [SMALL_STATE(90)] = 1235,
  [SMALL_STATE(91)] = 1239,
  [SMALL_STATE(92)] = 1243,
  [SMALL_STATE(93)] = 1247,
  [SMALL_STATE(94)] = 1251,
  [SMALL_STATE(95)] = 1255,
  [SMALL_STATE(96)] = 1259,
  [SMALL_STATE(97)] = 1263,
  [SMALL_STATE(98)] = 1267,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [7] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(16),
  [10] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(74),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(25),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(18),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(16),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 4),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 4),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 6),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 6),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_piecewise_closure, 5),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_piecewise_closure, 5),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 3),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_piecewise_closure, 4),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_piecewise_closure, 4),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 5),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 5),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_piecewise_closure, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_piecewise_closure, 3),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_term, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(31),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arm_repeat1, 2),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(18),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(60),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(18),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(31),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(18),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(60),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(18),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arm_repeat1, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 6),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_type_repeat1, 2), SHIFT_REPEAT(46),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_type_repeat1, 2),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_type_repeat1, 2), SHIFT_REPEAT(44),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 5),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arm, 4),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arm, 3),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_expression, 1),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_expression, 3),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arm, 5),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(94),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_non_piecewise_closure, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_piecewise_closure_repeat1, 2), SHIFT_REPEAT(79),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_piecewise_closure_repeat1, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_name, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 5),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 6),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 4),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_closure, 1),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_signature, 2),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [275] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_curse(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
