#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_fn = 1,
  anon_sym_EQ = 2,
  anon_sym_COLON = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_COMMA = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_PIPE = 10,
  anon_sym_true = 11,
  anon_sym_false = 12,
  anon_sym_in = 13,
  sym_identifier = 14,
  sym_named_type = 15,
  sym_integer = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_DOT = 20,
  anon_sym_DOT_DOT = 21,
  anon_sym_SEMI = 22,
  anon_sym_PERCENT = 23,
  anon_sym_SLASH = 24,
  anon_sym_LT = 25,
  anon_sym_GT = 26,
  anon_sym_LT_EQ = 27,
  anon_sym_GT_EQ = 28,
  sym_source_file = 29,
  sym__definition = 30,
  sym_function_definition = 31,
  sym_type_signature = 32,
  sym_type = 33,
  sym_start_type = 34,
  sym_closure = 35,
  sym_non_piecewise_closure = 36,
  sym_piecewise_closure = 37,
  sym_arm = 38,
  sym_expression = 39,
  sym_end_expression = 40,
  sym_end_term = 41,
  sym_term = 42,
  sym_param = 43,
  sym_pattern = 44,
  sym_param_name = 45,
  sym_literal = 46,
  sym_symbol = 47,
  aux_sym_source_file_repeat1 = 48,
  aux_sym_type_signature_repeat1 = 49,
  aux_sym_start_type_repeat1 = 50,
  aux_sym_piecewise_closure_repeat1 = 51,
  aux_sym_arm_repeat1 = 52,
  aux_sym_term_repeat1 = 53,
  aux_sym_pattern_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_fn] = "fn",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PIPE] = "|",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_in] = "in",
  [sym_identifier] = "identifier",
  [sym_named_type] = "named_type",
  [sym_integer] = "integer",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_DOT] = ".",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_SEMI] = ";",
  [anon_sym_PERCENT] = "%",
  [anon_sym_SLASH] = "/",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_function_definition] = "function_definition",
  [sym_type_signature] = "type_signature",
  [sym_type] = "type",
  [sym_start_type] = "start_type",
  [sym_closure] = "closure",
  [sym_non_piecewise_closure] = "non_piecewise_closure",
  [sym_piecewise_closure] = "piecewise_closure",
  [sym_arm] = "arm",
  [sym_expression] = "expression",
  [sym_end_expression] = "end_expression",
  [sym_end_term] = "end_term",
  [sym_term] = "term",
  [sym_param] = "param",
  [sym_pattern] = "pattern",
  [sym_param_name] = "param_name",
  [sym_literal] = "literal",
  [sym_symbol] = "symbol",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_type_signature_repeat1] = "type_signature_repeat1",
  [aux_sym_start_type_repeat1] = "start_type_repeat1",
  [aux_sym_piecewise_closure_repeat1] = "piecewise_closure_repeat1",
  [aux_sym_arm_repeat1] = "arm_repeat1",
  [aux_sym_term_repeat1] = "term_repeat1",
  [aux_sym_pattern_repeat1] = "pattern_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_in] = anon_sym_in,
  [sym_identifier] = sym_identifier,
  [sym_named_type] = sym_named_type,
  [sym_integer] = sym_integer,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_function_definition] = sym_function_definition,
  [sym_type_signature] = sym_type_signature,
  [sym_type] = sym_type,
  [sym_start_type] = sym_start_type,
  [sym_closure] = sym_closure,
  [sym_non_piecewise_closure] = sym_non_piecewise_closure,
  [sym_piecewise_closure] = sym_piecewise_closure,
  [sym_arm] = sym_arm,
  [sym_expression] = sym_expression,
  [sym_end_expression] = sym_end_expression,
  [sym_end_term] = sym_end_term,
  [sym_term] = sym_term,
  [sym_param] = sym_param,
  [sym_pattern] = sym_pattern,
  [sym_param_name] = sym_param_name,
  [sym_literal] = sym_literal,
  [sym_symbol] = sym_symbol,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_type_signature_repeat1] = aux_sym_type_signature_repeat1,
  [aux_sym_start_type_repeat1] = aux_sym_start_type_repeat1,
  [aux_sym_piecewise_closure_repeat1] = aux_sym_piecewise_closure_repeat1,
  [aux_sym_arm_repeat1] = aux_sym_arm_repeat1,
  [aux_sym_term_repeat1] = aux_sym_term_repeat1,
  [aux_sym_pattern_repeat1] = aux_sym_pattern_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_named_type] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_type_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_start_type] = {
    .visible = true,
    .named = true,
  },
  [sym_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_non_piecewise_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_piecewise_closure] = {
    .visible = true,
    .named = true,
  },
  [sym_arm] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_end_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_end_term] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_param_name] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_signature_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_piecewise_closure_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arm_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '%') ADVANCE(46);
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == '*') ADVANCE(42);
      if (lookahead == '+') ADVANCE(40);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == ';') ADVANCE(45);
      if (lookahead == '<') ADVANCE(48);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(49);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(38);
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(17);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(29);
      if (lookahead == 'i') ADVANCE(33);
      if (lookahead == 't') ADVANCE(34);
      if (lookahead == '|') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(6);
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(4);
      END_STATE();
    case 11:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_in);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_named_type);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 11},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [sym_named_type] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(101),
    [sym__definition] = STATE(55),
    [sym_function_definition] = STATE(55),
    [aux_sym_source_file_repeat1] = STATE(55),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(5),
  },
  [2] = {
    [sym_non_piecewise_closure] = STATE(46),
    [sym_piecewise_closure] = STATE(20),
    [sym_arm] = STATE(48),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(78),
    [sym_end_term] = STATE(50),
    [sym_term] = STATE(21),
    [sym_literal] = STATE(20),
    [sym_symbol] = STATE(20),
    [aux_sym_term_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_in] = ACTIONS(17),
    [sym_integer] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [3] = {
    [sym_non_piecewise_closure] = STATE(46),
    [sym_piecewise_closure] = STATE(20),
    [sym_arm] = STATE(48),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(102),
    [sym_end_term] = STATE(50),
    [sym_term] = STATE(21),
    [sym_literal] = STATE(20),
    [sym_symbol] = STATE(20),
    [aux_sym_term_repeat1] = STATE(3),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_LPAREN] = ACTIONS(24),
    [anon_sym_RPAREN] = ACTIONS(27),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_PIPE] = ACTIONS(32),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [anon_sym_in] = ACTIONS(35),
    [sym_integer] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(21),
    [anon_sym_DOT] = ACTIONS(38),
    [anon_sym_DOT_DOT] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(21),
    [anon_sym_SLASH] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(38),
    [anon_sym_GT] = ACTIONS(38),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
  },
  [4] = {
    [sym_non_piecewise_closure] = STATE(46),
    [sym_piecewise_closure] = STATE(20),
    [sym_arm] = STATE(48),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(91),
    [sym_end_term] = STATE(50),
    [sym_term] = STATE(21),
    [sym_literal] = STATE(20),
    [sym_symbol] = STATE(20),
    [aux_sym_term_repeat1] = STATE(2),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_in] = ACTIONS(17),
    [sym_integer] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [5] = {
    [sym_non_piecewise_closure] = STATE(46),
    [sym_piecewise_closure] = STATE(20),
    [sym_arm] = STATE(48),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(79),
    [sym_end_term] = STATE(50),
    [sym_term] = STATE(21),
    [sym_literal] = STATE(20),
    [sym_symbol] = STATE(20),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_in] = ACTIONS(17),
    [sym_integer] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [6] = {
    [sym_non_piecewise_closure] = STATE(46),
    [sym_piecewise_closure] = STATE(20),
    [sym_arm] = STATE(48),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(51),
    [sym_end_term] = STATE(50),
    [sym_term] = STATE(21),
    [sym_literal] = STATE(20),
    [sym_symbol] = STATE(20),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_in] = ACTIONS(17),
    [sym_integer] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [7] = {
    [sym_non_piecewise_closure] = STATE(46),
    [sym_piecewise_closure] = STATE(20),
    [sym_arm] = STATE(48),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(47),
    [sym_end_term] = STATE(50),
    [sym_term] = STATE(21),
    [sym_literal] = STATE(20),
    [sym_symbol] = STATE(20),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_in] = ACTIONS(17),
    [sym_integer] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
  [8] = {
    [sym_non_piecewise_closure] = STATE(46),
    [sym_piecewise_closure] = STATE(20),
    [sym_arm] = STATE(48),
    [sym_expression] = STATE(23),
    [sym_end_expression] = STATE(49),
    [sym_end_term] = STATE(50),
    [sym_term] = STATE(21),
    [sym_literal] = STATE(20),
    [sym_symbol] = STATE(20),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_PIPE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_in] = ACTIONS(17),
    [sym_integer] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_DOT] = ACTIONS(19),
    [anon_sym_DOT_DOT] = ACTIONS(7),
    [anon_sym_SEMI] = ACTIONS(7),
    [anon_sym_PERCENT] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      sym_term,
    STATE(46), 1,
      sym_non_piecewise_closure,
    STATE(48), 1,
      sym_arm,
    STATE(54), 1,
      sym_end_term,
    ACTIONS(19), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    STATE(20), 3,
      sym_piecewise_closure,
      sym_literal,
      sym_symbol,
    ACTIONS(17), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
    ACTIONS(7), 10,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [50] = 2,
    ACTIONS(47), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [80] = 2,
    ACTIONS(51), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(49), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [110] = 2,
    ACTIONS(55), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [140] = 2,
    ACTIONS(59), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [170] = 2,
    ACTIONS(63), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [200] = 2,
    ACTIONS(67), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(65), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [230] = 2,
    ACTIONS(71), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [260] = 2,
    ACTIONS(75), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(73), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [290] = 2,
    ACTIONS(79), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [320] = 2,
    ACTIONS(83), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [350] = 2,
    ACTIONS(87), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(85), 22,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [380] = 3,
    ACTIONS(93), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(91), 16,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [411] = 3,
    ACTIONS(97), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(95), 16,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [442] = 7,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym_term,
    ACTIONS(19), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    STATE(20), 3,
      sym_piecewise_closure,
      sym_literal,
      sym_symbol,
    ACTIONS(17), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
    ACTIONS(7), 10,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [480] = 2,
    ACTIONS(99), 3,
      anon_sym_DOT,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(27), 18,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_PIPE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_integer,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_DOT_DOT,
      anon_sym_SEMI,
      anon_sym_PERCENT,
      anon_sym_SLASH,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [506] = 9,
    ACTIONS(101), 1,
      anon_sym_LPAREN,
    ACTIONS(104), 1,
      anon_sym_PIPE,
    ACTIONS(109), 1,
      sym_identifier,
    ACTIONS(112), 1,
      sym_integer,
    STATE(25), 1,
      aux_sym_arm_repeat1,
    STATE(83), 1,
      sym_pattern,
    STATE(99), 1,
      sym_param,
    STATE(72), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(106), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [537] = 9,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_PIPE,
    ACTIONS(121), 1,
      sym_identifier,
    STATE(27), 1,
      aux_sym_arm_repeat1,
    STATE(77), 1,
      sym_param,
    STATE(83), 1,
      sym_pattern,
    STATE(72), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(119), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [568] = 9,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(123), 1,
      anon_sym_PIPE,
    STATE(25), 1,
      aux_sym_arm_repeat1,
    STATE(83), 1,
      sym_pattern,
    STATE(89), 1,
      sym_param,
    STATE(72), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(119), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [599] = 8,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    STATE(29), 1,
      aux_sym_pattern_repeat1,
    STATE(76), 1,
      sym_pattern,
    STATE(72), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(119), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [627] = 8,
    ACTIONS(127), 1,
      anon_sym_LPAREN,
    ACTIONS(130), 1,
      anon_sym_RPAREN,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(138), 1,
      sym_integer,
    STATE(29), 1,
      aux_sym_pattern_repeat1,
    STATE(96), 1,
      sym_pattern,
    STATE(72), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(132), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [655] = 8,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(141), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_pattern_repeat1,
    STATE(82), 1,
      sym_pattern,
    STATE(72), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(119), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [683] = 7,
    ACTIONS(17), 1,
      sym_integer,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_pattern,
    STATE(72), 2,
      sym_param_name,
      sym_literal,
    ACTIONS(119), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
  [708] = 2,
    ACTIONS(104), 3,
      anon_sym_LPAREN,
      anon_sym_PIPE,
      sym_integer,
    ACTIONS(145), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_identifier,
  [720] = 2,
    ACTIONS(130), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_integer,
    ACTIONS(147), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_in,
      sym_identifier,
  [732] = 5,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    STATE(48), 1,
      sym_arm,
    STATE(75), 1,
      sym_closure,
    STATE(90), 2,
      sym_non_piecewise_closure,
      sym_piecewise_closure,
  [749] = 6,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
    ACTIONS(153), 1,
      sym_named_type,
    STATE(43), 1,
      sym_start_type,
    STATE(44), 1,
      aux_sym_start_type_repeat1,
    STATE(81), 1,
      sym_type,
  [768] = 1,
    ACTIONS(155), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [777] = 1,
    ACTIONS(157), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [786] = 1,
    ACTIONS(159), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [795] = 6,
    ACTIONS(161), 1,
      anon_sym_LPAREN,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    ACTIONS(166), 1,
      sym_named_type,
    STATE(39), 1,
      aux_sym_start_type_repeat1,
    STATE(43), 1,
      sym_start_type,
    STATE(94), 1,
      sym_type,
  [814] = 1,
    ACTIONS(169), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [823] = 1,
    ACTIONS(171), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [832] = 5,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    STATE(48), 1,
      sym_arm,
    STATE(85), 1,
      sym_closure,
    STATE(90), 2,
      sym_non_piecewise_closure,
      sym_piecewise_closure,
  [849] = 4,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      sym_named_type,
    STATE(95), 1,
      sym_start_type,
    ACTIONS(173), 3,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [864] = 6,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      sym_named_type,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      aux_sym_start_type_repeat1,
    STATE(43), 1,
      sym_start_type,
    STATE(84), 1,
      sym_type,
  [883] = 1,
    ACTIONS(177), 6,
      anon_sym_EQ,
      anon_sym_DASH_GT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_named_type,
  [892] = 1,
    ACTIONS(89), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [900] = 1,
    ACTIONS(179), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [908] = 1,
    ACTIONS(181), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [916] = 1,
    ACTIONS(183), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [924] = 1,
    ACTIONS(185), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [932] = 1,
    ACTIONS(187), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [940] = 5,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      sym_named_type,
    ACTIONS(189), 1,
      anon_sym_RPAREN,
    STATE(43), 1,
      sym_start_type,
    STATE(87), 1,
      sym_type,
  [956] = 3,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
    ACTIONS(193), 1,
      anon_sym_fn,
    STATE(53), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [968] = 1,
    ACTIONS(196), 5,
      ts_builtin_sym_end,
      anon_sym_fn,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [976] = 3,
    ACTIONS(5), 1,
      anon_sym_fn,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
    STATE(53), 3,
      sym__definition,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [988] = 5,
    ACTIONS(200), 1,
      anon_sym_EQ,
    ACTIONS(202), 1,
      anon_sym_COLON,
    ACTIONS(204), 1,
      sym_named_type,
    STATE(68), 1,
      aux_sym_type_signature_repeat1,
    STATE(100), 1,
      sym_type_signature,
  [1004] = 4,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      sym_named_type,
    STATE(43), 1,
      sym_start_type,
    STATE(98), 1,
      sym_type,
  [1017] = 4,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      sym_named_type,
    STATE(43), 1,
      sym_start_type,
    STATE(67), 1,
      sym_type,
  [1030] = 4,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(153), 1,
      sym_named_type,
    STATE(43), 1,
      sym_start_type,
    STATE(92), 1,
      sym_type,
  [1043] = 1,
    ACTIONS(206), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1049] = 1,
    ACTIONS(208), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1055] = 1,
    ACTIONS(164), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_named_type,
  [1061] = 3,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_piecewise_closure_repeat1,
  [1071] = 3,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_piecewise_closure_repeat1,
  [1081] = 3,
    ACTIONS(218), 1,
      anon_sym_COLON,
    ACTIONS(220), 1,
      sym_named_type,
    STATE(65), 1,
      aux_sym_type_signature_repeat1,
  [1091] = 3,
    ACTIONS(223), 1,
      anon_sym_COMMA,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    STATE(66), 1,
      aux_sym_piecewise_closure_repeat1,
  [1101] = 1,
    ACTIONS(228), 3,
      anon_sym_EQ,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1107] = 3,
    ACTIONS(230), 1,
      anon_sym_COLON,
    ACTIONS(232), 1,
      sym_named_type,
    STATE(65), 1,
      aux_sym_type_signature_repeat1,
  [1117] = 1,
    ACTIONS(234), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1123] = 3,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      sym_arm,
  [1133] = 1,
    ACTIONS(238), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1139] = 1,
    ACTIONS(240), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1145] = 1,
    ACTIONS(242), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1151] = 3,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
    STATE(86), 1,
      sym_arm,
  [1161] = 1,
    ACTIONS(244), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1166] = 2,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    ACTIONS(248), 1,
      anon_sym_COMMA,
  [1173] = 2,
    ACTIONS(123), 1,
      anon_sym_PIPE,
    ACTIONS(250), 1,
      anon_sym_COMMA,
  [1180] = 2,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    ACTIONS(254), 1,
      anon_sym_COMMA,
  [1187] = 2,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    ACTIONS(258), 1,
      anon_sym_COMMA,
  [1194] = 2,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    STATE(86), 1,
      sym_arm,
  [1201] = 2,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    ACTIONS(260), 1,
      anon_sym_COMMA,
  [1208] = 2,
    ACTIONS(125), 1,
      anon_sym_RPAREN,
    ACTIONS(248), 1,
      anon_sym_COMMA,
  [1215] = 1,
    ACTIONS(262), 2,
      anon_sym_COMMA,
      anon_sym_PIPE,
  [1220] = 2,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RPAREN,
  [1227] = 1,
    ACTIONS(266), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1232] = 1,
    ACTIONS(226), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1237] = 2,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    ACTIONS(270), 1,
      anon_sym_COMMA,
  [1244] = 2,
    ACTIONS(15), 1,
      anon_sym_PIPE,
    STATE(63), 1,
      sym_arm,
  [1251] = 2,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_PIPE,
  [1258] = 1,
    ACTIONS(274), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [1263] = 2,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(254), 1,
      anon_sym_COMMA,
  [1270] = 1,
    ACTIONS(276), 1,
      anon_sym_EQ,
  [1274] = 1,
    ACTIONS(278), 1,
      anon_sym_COMMA,
  [1278] = 1,
    ACTIONS(260), 1,
      anon_sym_COMMA,
  [1282] = 1,
    ACTIONS(280), 1,
      anon_sym_DASH_GT,
  [1286] = 1,
    ACTIONS(248), 1,
      anon_sym_COMMA,
  [1290] = 1,
    ACTIONS(282), 1,
      sym_identifier,
  [1294] = 1,
    ACTIONS(284), 1,
      anon_sym_EQ,
  [1298] = 1,
    ACTIONS(250), 1,
      anon_sym_COMMA,
  [1302] = 1,
    ACTIONS(286), 1,
      anon_sym_EQ,
  [1306] = 1,
    ACTIONS(288), 1,
      ts_builtin_sym_end,
  [1310] = 1,
    ACTIONS(254), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 50,
  [SMALL_STATE(11)] = 80,
  [SMALL_STATE(12)] = 110,
  [SMALL_STATE(13)] = 140,
  [SMALL_STATE(14)] = 170,
  [SMALL_STATE(15)] = 200,
  [SMALL_STATE(16)] = 230,
  [SMALL_STATE(17)] = 260,
  [SMALL_STATE(18)] = 290,
  [SMALL_STATE(19)] = 320,
  [SMALL_STATE(20)] = 350,
  [SMALL_STATE(21)] = 380,
  [SMALL_STATE(22)] = 411,
  [SMALL_STATE(23)] = 442,
  [SMALL_STATE(24)] = 480,
  [SMALL_STATE(25)] = 506,
  [SMALL_STATE(26)] = 537,
  [SMALL_STATE(27)] = 568,
  [SMALL_STATE(28)] = 599,
  [SMALL_STATE(29)] = 627,
  [SMALL_STATE(30)] = 655,
  [SMALL_STATE(31)] = 683,
  [SMALL_STATE(32)] = 708,
  [SMALL_STATE(33)] = 720,
  [SMALL_STATE(34)] = 732,
  [SMALL_STATE(35)] = 749,
  [SMALL_STATE(36)] = 768,
  [SMALL_STATE(37)] = 777,
  [SMALL_STATE(38)] = 786,
  [SMALL_STATE(39)] = 795,
  [SMALL_STATE(40)] = 814,
  [SMALL_STATE(41)] = 823,
  [SMALL_STATE(42)] = 832,
  [SMALL_STATE(43)] = 849,
  [SMALL_STATE(44)] = 864,
  [SMALL_STATE(45)] = 883,
  [SMALL_STATE(46)] = 892,
  [SMALL_STATE(47)] = 900,
  [SMALL_STATE(48)] = 908,
  [SMALL_STATE(49)] = 916,
  [SMALL_STATE(50)] = 924,
  [SMALL_STATE(51)] = 932,
  [SMALL_STATE(52)] = 940,
  [SMALL_STATE(53)] = 956,
  [SMALL_STATE(54)] = 968,
  [SMALL_STATE(55)] = 976,
  [SMALL_STATE(56)] = 988,
  [SMALL_STATE(57)] = 1004,
  [SMALL_STATE(58)] = 1017,
  [SMALL_STATE(59)] = 1030,
  [SMALL_STATE(60)] = 1043,
  [SMALL_STATE(61)] = 1049,
  [SMALL_STATE(62)] = 1055,
  [SMALL_STATE(63)] = 1061,
  [SMALL_STATE(64)] = 1071,
  [SMALL_STATE(65)] = 1081,
  [SMALL_STATE(66)] = 1091,
  [SMALL_STATE(67)] = 1101,
  [SMALL_STATE(68)] = 1107,
  [SMALL_STATE(69)] = 1117,
  [SMALL_STATE(70)] = 1123,
  [SMALL_STATE(71)] = 1133,
  [SMALL_STATE(72)] = 1139,
  [SMALL_STATE(73)] = 1145,
  [SMALL_STATE(74)] = 1151,
  [SMALL_STATE(75)] = 1161,
  [SMALL_STATE(76)] = 1166,
  [SMALL_STATE(77)] = 1173,
  [SMALL_STATE(78)] = 1180,
  [SMALL_STATE(79)] = 1187,
  [SMALL_STATE(80)] = 1194,
  [SMALL_STATE(81)] = 1201,
  [SMALL_STATE(82)] = 1208,
  [SMALL_STATE(83)] = 1215,
  [SMALL_STATE(84)] = 1220,
  [SMALL_STATE(85)] = 1227,
  [SMALL_STATE(86)] = 1232,
  [SMALL_STATE(87)] = 1237,
  [SMALL_STATE(88)] = 1244,
  [SMALL_STATE(89)] = 1251,
  [SMALL_STATE(90)] = 1258,
  [SMALL_STATE(91)] = 1263,
  [SMALL_STATE(92)] = 1270,
  [SMALL_STATE(93)] = 1274,
  [SMALL_STATE(94)] = 1278,
  [SMALL_STATE(95)] = 1282,
  [SMALL_STATE(96)] = 1286,
  [SMALL_STATE(97)] = 1290,
  [SMALL_STATE(98)] = 1294,
  [SMALL_STATE(99)] = 1298,
  [SMALL_STATE(100)] = 1302,
  [SMALL_STATE(101)] = 1306,
  [SMALL_STATE(102)] = 1310,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(16),
  [24] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(88),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(26),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(18),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2), SHIFT_REPEAT(16),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 5),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 5),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 4),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 4),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 3),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_piecewise_closure, 5),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_piecewise_closure, 5),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_piecewise_closure, 4),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_piecewise_closure, 4),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 1),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_piecewise_closure, 3),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_piecewise_closure, 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 6),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 6),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_term, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(31),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arm_repeat1, 2),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(18),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(60),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arm_repeat1, 2), SHIFT_REPEAT(18),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(31),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(18),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(60),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pattern_repeat1, 2), SHIFT_REPEAT(18),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arm_repeat1, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pattern_repeat1, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 2),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_type_repeat1, 2), SHIFT_REPEAT(52),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_type_repeat1, 2),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_type_repeat1, 2), SHIFT_REPEAT(37),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 6),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 4),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_type, 5),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arm, 4),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_non_piecewise_closure, 1),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arm, 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_expression, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arm, 5),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(97),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_expression, 3),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param_name, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_signature_repeat1, 2),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_signature_repeat1, 2), SHIFT_REPEAT(65),
  [223] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_piecewise_closure_repeat1, 2), SHIFT_REPEAT(80),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_piecewise_closure_repeat1, 2),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 4),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 4),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 5),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 1),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pattern, 6),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 5),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 1),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_closure, 1),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_signature, 3),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_signature, 2),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [288] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_curse(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
